2025-08-02 13:11:57,395 INFO: AppointmentCRM startup [in C:\Users\Lorenzo\Desktop\Controllo\app_restructured\app.py:66]
2025-08-02 13:12:12,099 INFO: AppointmentCRM startup [in C:\Users\Lorenzo\Desktop\Controllo\app_restructured\app.py:66]
2025-08-02 13:12:37,923 INFO: AppointmentCRM startup [in C:\Users\Lorenzo\Desktop\Controllo\app_restructured\app.py:66]
2025-08-02 13:19:27,639 INFO: AppointmentCRM startup [in C:\Users\Lorenzo\Desktop\Controllo\app_restructured\app.py:66]
2025-08-02 13:19:49,052 INFO: AppointmentCRM startup [in C:\Users\Lorenzo\Desktop\Controllo\app_restructured\app.py:66]
2025-08-02 13:21:46,264 INFO: AppointmentCRM startup [in C:\Users\Lorenzo\Desktop\Controllo\app_restructured\app.py:66]
2025-08-02 13:26:05,414 INFO: Comando admin eseguito da admin: netstat -tuln [in C:\Users\Lorenzo\Desktop\Controllo\app_restructured\routes\admin.py:280]
2025-08-02 13:35:20,132 INFO: AppointmentCRM startup [in C:\Users\Lorenzo\Desktop\Controllo\app_restructured\app.py:66]
2025-08-02 13:35:26,982 ERROR: Exception on /admin/dashboard [GET] [in C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\Lorenzo\Desktop\Controllo\app_restructured\routes\admin.py", line 20, in decorated_function
    return f(*args, **kwargs)
  File "C:\Users\Lorenzo\Desktop\Controllo\app_restructured\routes\admin.py", line 55, in dashboard
    return render_template('admin/dashboard.html', data=data)
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 1084, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Lorenzo\Desktop\Controllo\app_restructured\templates\admin\dashboard.html", line 786, in template
    {% endblock %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endblock'.
2025-08-02 13:35:29,605 ERROR: Exception on /admin/dashboard [GET] [in C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\Lorenzo\Desktop\Controllo\app_restructured\routes\admin.py", line 20, in decorated_function
    return f(*args, **kwargs)
  File "C:\Users\Lorenzo\Desktop\Controllo\app_restructured\routes\admin.py", line 55, in dashboard
    return render_template('admin/dashboard.html', data=data)
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 1084, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Lorenzo\Desktop\Controllo\app_restructured\templates\admin\dashboard.html", line 786, in template
    {% endblock %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endblock'.
2025-08-02 13:35:31,445 ERROR: Exception on /admin/dashboard [GET] [in C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\Lorenzo\Desktop\Controllo\app_restructured\routes\admin.py", line 20, in decorated_function
    return f(*args, **kwargs)
  File "C:\Users\Lorenzo\Desktop\Controllo\app_restructured\routes\admin.py", line 55, in dashboard
    return render_template('admin/dashboard.html', data=data)
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 1084, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Lorenzo\Desktop\Controllo\app_restructured\templates\admin\dashboard.html", line 786, in template
    {% endblock %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endblock'.
