2025-08-02 13:38:11,131 ERROR: Exception on /clients [GET] [in C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\Lorenzo\Desktop\Controllo\app_restructured\routes\main.py", line 191, in clients
    return render_template('clients.html',
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Lorenzo\Desktop\Controllo\app_restructured\templates\clients.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Lorenzo\Desktop\Controllo\app_restructured\templates\base.html", line 99, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\Lorenzo\Desktop\Controllo\app_restructured\templates\clients.html", line 126, in block 'content'
    {% block scripts %}
  File "C:\Users\Lorenzo\Desktop\Controllo\app_restructured\templates\clients.html", line 217, in block 'scripts'
    window.location.href = "{{ url_for('clients') }}?" + params.toString();
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'clients'. Did you mean 'main.clients' instead?
2025-08-02 13:40:21,903 INFO: AppointmentCRM startup [in C:\Users\Lorenzo\Desktop\Controllo\app_restructured\app.py:66]
2025-08-02 14:10:16,560 INFO: AppointmentCRM startup [in C:\Users\Lorenzo\Desktop\Controllo\app_restructured\app.py:66]
2025-08-02 14:10:22,258 ERROR: Exception on /admin/dashboard [GET] [in C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\Lorenzo\Desktop\Controllo\app_restructured\routes\admin.py", line 20, in decorated_function
    return f(*args, **kwargs)
  File "C:\Users\Lorenzo\Desktop\Controllo\app_restructured\routes\admin.py", line 55, in dashboard
    return render_template('admin/dashboard.html', data=data)
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 1084, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Lorenzo\Desktop\Controllo\app_restructured\templates\admin\dashboard.html", line 1064, in template
    {% endblock %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endblock'.
2025-08-02 14:30:30,142 ERROR: Exception on /admin/dashboard [GET] [in C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\Lorenzo\Desktop\Controllo\app_restructured\routes\admin.py", line 20, in decorated_function
    return f(*args, **kwargs)
  File "C:\Users\Lorenzo\Desktop\Controllo\app_restructured\routes\admin.py", line 55, in dashboard
    return render_template('admin/dashboard.html', data=data)
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 1084, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\Lorenzo\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Lorenzo\Desktop\Controllo\app_restructured\templates\admin\dashboard.html", line 1064, in template
    {% endblock %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endblock'.
2025-08-02 14:34:17,040 INFO: AppointmentCRM startup [in C:\Users\Lorenzo\Desktop\Controllo\app_restructured\app.py:66]
2025-08-02 14:34:21,641 INFO: AppointmentCRM startup [in C:\Users\Lorenzo\Desktop\Controllo\app_restructured\app.py:66]
2025-08-02 14:35:23,403 INFO: AppointmentCRM startup [in C:\Users\Lorenzo\Desktop\Controllo\app_restructured\app.py:66]
2025-08-02 14:36:04,775 INFO: AppointmentCRM startup [in C:\Users\Lorenzo\Desktop\Controllo\app_restructured\app.py:66]
2025-08-02 14:39:06,568 INFO: AppointmentCRM startup [in C:\Users\Lorenzo\Desktop\Controllo\app_restructured\app.py:66]
